In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv(r"F://insurance.csv")

In [3]:
data

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [4]:
data['sex'].replace(to_replace=['male','female'],value=[0,1],inplace=True)

In [5]:
data

age  sex     bmi  children smoker     region      charges
0      19    1  27.900         0    yes  southwest  16884.92400
1      18    0  33.770         1     no  southeast   1725.55230
2      28    0  33.000         3     no  southeast   4449.46200
3      33    0  22.705         0     no  northwest  21984.47061
4      32    0  28.880         0     no  northwest   3866.85520
...   ...  ...     ...       ...    ...        ...          ...
1333   50    0  30.970         3     no  northwest  10600.54830
1334   18    1  31.920         0     no  northeast   2205.98080
1335   18    1  36.850         0     no  southeast   1629.83350
1336   21    1  25.800         0     no  southwest   2007.94500
1337   61    1  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [6]:
data['smoker'].replace(to_replace=['no','yes'],value=[0,1],inplace=True)

In [7]:
data

age  sex     bmi  children  smoker     region      charges
0      19    1  27.900         0       1  southwest  16884.92400
1      18    0  33.770         1       0  southeast   1725.55230
2      28    0  33.000         3       0  southeast   4449.46200
3      33    0  22.705         0       0  northwest  21984.47061
4      32    0  28.880         0       0  northwest   3866.85520
...   ...  ...     ...       ...     ...        ...          ...
1333   50    0  30.970         3       0  northwest  10600.54830
1334   18    1  31.920         0       0  northeast   2205.98080
1335   18    1  36.850         0       0  southeast   1629.83350
1336   21    1  25.800         0       0  southwest   2007.94500
1337   61    1  29.070         0       1  northwest  29141.36030

[1338 rows x 7 columns]

In [8]:
data['region'].replace(to_replace=data['region'].unique(),value=list(range(len(data['region'].unique()))),inplace=True)

In [9]:
data

age  sex     bmi  children  smoker  region      charges
0      19    1  27.900         0       1       0  16884.92400
1      18    0  33.770         1       0       1   1725.55230
2      28    0  33.000         3       0       1   4449.46200
3      33    0  22.705         0       0       2  21984.47061
4      32    0  28.880         0       0       2   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50    0  30.970         3       0       2  10600.54830
1334   18    1  31.920         0       0       3   2205.98080
1335   18    1  36.850         0       0       1   1629.83350
1336   21    1  25.800         0       0       0   2007.94500
1337   61    1  29.070         0       1       2  29141.36030

[1338 rows x 7 columns]

In [10]:
region_variable_ohe=np.eye(len(data['region'].unique()),len(data['region'].unique()))[data['region']]

In [11]:
region_variable_ohe

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       ...,
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.]])

In [12]:
process_data=data.drop(['region'],axis=1)

In [13]:
process_data

age  sex     bmi  children  smoker      charges
0      19    1  27.900         0       1  16884.92400
1      18    0  33.770         1       0   1725.55230
2      28    0  33.000         3       0   4449.46200
3      33    0  22.705         0       0  21984.47061
4      32    0  28.880         0       0   3866.85520
...   ...  ...     ...       ...     ...          ...
1333   50    0  30.970         3       0  10600.54830
1334   18    1  31.920         0       0   2205.98080
1335   18    1  36.850         0       0   1629.83350
1336   21    1  25.800         0       0   2007.94500
1337   61    1  29.070         0       1  29141.36030

[1338 rows x 6 columns]

In [14]:
region_variable_df=pd.DataFrame(data=region_variable_ohe,columns=['Region 0','Region 2','Region 3','Region 4'])

In [15]:
region_variable_df

Region 0  Region 2  Region 3  Region 4
0          1.0       0.0       0.0       0.0
1          0.0       1.0       0.0       0.0
2          0.0       1.0       0.0       0.0
3          0.0       0.0       1.0       0.0
4          0.0       0.0       1.0       0.0
...        ...       ...       ...       ...
1333       0.0       0.0       1.0       0.0
1334       0.0       0.0       0.0       1.0
1335       0.0       1.0       0.0       0.0
1336       1.0       0.0       0.0       0.0
1337       0.0       0.0       1.0       0.0

[1338 rows x 4 columns]

In [16]:
processed_data=pd.concat([process_data,region_variable_df],axis=1)

In [17]:
processed_data

age  sex     bmi  children  smoker      charges  Region 0  Region 2  \
0      19    1  27.900         0       1  16884.92400       1.0       0.0   
1      18    0  33.770         1       0   1725.55230       0.0       1.0   
2      28    0  33.000         3       0   4449.46200       0.0       1.0   
3      33    0  22.705         0       0  21984.47061       0.0       0.0   
4      32    0  28.880         0       0   3866.85520       0.0       0.0   
...   ...  ...     ...       ...     ...          ...       ...       ...   
1333   50    0  30.970         3       0  10600.54830       0.0       0.0   
1334   18    1  31.920         0       0   2205.98080       0.0       0.0   
1335   18    1  36.850         0       0   1629.83350       0.0       1.0   
1336   21    1  25.800         0       0   2007.94500       1.0       0.0   
1337   61    1  29.070         0       1  29141.36030       0.0       0.0   

      Region 3  Region 4  
0          0.0       0.0  
1          0.0       0.0  
2          0.0       0.0  
3          1.0       0.0  
4          1.0       0.0  
...        ...       ...  
1333       1.0       0.0  
1334       0.0       1.0  
1335       0.0       0.0  
1336       0.0       0.0  
1337       1.0       0.0  

[1338 rows x 10 columns]

In [18]:
gt_labels=processed_data['charges']
processed_data.drop(['charges'],inplace=True,axis=1)

In [19]:
processed_data['charges']=gt_labels

In [20]:
processed_data

age  sex     bmi  children  smoker  Region 0  Region 2  Region 3  \
0      19    1  27.900         0       1       1.0       0.0       0.0   
1      18    0  33.770         1       0       0.0       1.0       0.0   
2      28    0  33.000         3       0       0.0       1.0       0.0   
3      33    0  22.705         0       0       0.0       0.0       1.0   
4      32    0  28.880         0       0       0.0       0.0       1.0   
...   ...  ...     ...       ...     ...       ...       ...       ...   
1333   50    0  30.970         3       0       0.0       0.0       1.0   
1334   18    1  31.920         0       0       0.0       0.0       0.0   
1335   18    1  36.850         0       0       0.0       1.0       0.0   
1336   21    1  25.800         0       0       1.0       0.0       0.0   
1337   61    1  29.070         0       1       0.0       0.0       1.0   

      Region 4      charges  
0          0.0  16884.92400  
1          0.0   1725.55230  
2          0.0   4449.46200  
3          0.0  21984.47061  
4          0.0   3866.85520  
...        ...          ...  
1333       0.0  10600.54830  
1334       1.0   2205.98080  
1335       0.0   1629.83350  
1336       0.0   2007.94500  
1337       0.0  29141.36030  

[1338 rows x 10 columns]

In [21]:
y=np.array(processed_data['charges']).reshape(processed_data.shape[0],1)
x_transpose=np.array(processed_data.drop(['charges'],axis=1))

In [22]:
y.shape

(1338, 1)

In [23]:
x_transpose.shape

(1338, 9)

In [24]:
x_transpose=(x_transpose-np.mean(x_transpose,axis=0))/np.std(x_transpose,axis=0)

In [25]:
x_transpose_df=pd.DataFrame(data=x_transpose)

In [26]:
x_transpose_df

0         1         2         3         4         5         6  \
0    -1.438764  1.010519 -0.453320 -0.908614  1.970587  1.765481 -0.611324   
1    -1.509965 -0.989591  0.509621 -0.078767 -0.507463 -0.566418  1.635795   
2    -0.797954 -0.989591  0.383307  1.580926 -0.507463 -0.566418  1.635795   
3    -0.441948 -0.989591 -1.305531 -0.908614 -0.507463 -0.566418 -0.611324   
4    -0.513149 -0.989591 -0.292556 -0.908614 -0.507463 -0.566418 -0.611324   
...        ...       ...       ...       ...       ...       ...       ...   
1333  0.768473 -0.989591  0.050297  1.580926 -0.507463 -0.566418 -0.611324   
1334 -1.509965  1.010519  0.206139 -0.908614 -0.507463 -0.566418 -0.611324   
1335 -1.509965  1.010519  1.014878 -0.908614 -0.507463 -0.566418  1.635795   
1336 -1.296362  1.010519 -0.797813 -0.908614 -0.507463  1.765481 -0.611324   
1337  1.551686  1.010519 -0.261388 -0.908614  1.970587 -0.566418 -0.611324   

             7         8  
0    -0.566418 -0.565267  
1    -0.566418 -0.565267  
2    -0.566418 -0.565267  
3     1.765481 -0.565267  
4     1.765481 -0.565267  
...        ...       ...  
1333  1.765481 -0.565267  
1334 -0.566418  1.769076  
1335 -0.566418 -0.565267  
1336 -0.566418 -0.565267  
1337  1.765481 -0.565267  

[1338 rows x 9 columns]

In [27]:
x_transpose_train=x_transpose[0:int(0.7*x_transpose.shape[0])]
x_transpose_cv=x_transpose[int(0.7*x_transpose.shape[0]):int(0.9*x_transpose.shape[0])]
x_transpose_test=x_transpose[int(0.9*x_transpose.shape[0]):]

In [47]:
y_train = (y[0:int(0.7*x_transpose.shape[0])] - np.mean(y[0:int(0.7*x_transpose.shape[0])]))/np.std(y[0:int(0.7*x_transpose.shape[0])])
y_cv = y[int(0.7*x_transpose.shape[0]):int(0.9*x_transpose.shape[0])]
y_test = y[int(0.9*x_transpose.shape[0]):]

In [48]:
n_train=x_transpose_train.shape[0]
m=x_transpose_train.shape[1]

In [49]:
def predicted_answers(theta0,theta,X_transpose):
    return theta0 + np.matmul(X_transpose,theta)

In [50]:
def neg_log_loss(labels,predicted_labels,theta,reg_strength):
    E = labels - predicted_labels
    return (1/labels.shape[0])*np.matmul(E.T,E) + (reg_strength*(np.linalg.norm(theta))**2/2)

In [51]:
# LINEAR REGRESSION IN MINI BATCH

In [52]:
def fit(step_size,reg_strength):
    theta0_initial = 0
    theta_initial = np.zeros((m,1))
    epsilon = step_size
    tol = 10**(-6)
    iterations = list()
    neg_log_loss_history = list()
    iteration_number = 0
    mini_batch_size = 72
    time_steps = n_train//mini_batch_size
    epoch_counter = 0 
    invalid_value_flag = 0 
    
    while(True):
        
        for i in range(0,time_steps):
            rand_indices = np.random.choice(a=np.arange(0,n_train),size=mini_batch_size,replace=False)
            x_transpose_mini_batch = x_transpose_train[rand_indices]
            train_labels_mini_batch = y_train[rand_indices]
            
            Predicted_answers_initial = predicted_answers(theta0_initial,theta_initial,
                                                          x_transpose_mini_batch)
            theta0_final = theta0_initial - epsilon*np.mean(Predicted_answers_initial-train_labels_mini_batch)
            theta_final = theta_initial - epsilon*((1/mini_batch_size)*np.matmul(x_transpose_mini_batch.T,
                                                                                (Predicted_answers_initial-train_labels_mini_batch))+(reg_strength*theta_initial))
            
            neg_log_loss_initial = neg_log_loss(train_labels_mini_batch,Predicted_answers_initial,
                                                theta_initial,reg_strength)
            
            predicted_answers_final = predicted_answers(theta0_final,theta_final,x_transpose_mini_batch)
            neg_log_loss_final = neg_log_loss(train_labels_mini_batch,predicted_answers_final,
                                             theta_final,reg_strength)
            
            if np.isnan(neg_log_loss_final[0][0]) == True:
                invalid_value_flag = 1
                break
                
            theta0_initial = theta0_final
            theta_initial = theta_final
            
            iterations.append(iteration_number)
            neg_log_loss_history.append(neg_log_loss_initial[0][0])
            
            iteration_number = iteration_number + 1
            
            #print("Iterations =",iteration_number,"Mean Squared Error Loss =",neg_log_loss_initial)
            
        epoch_counter = epoch_counter + 1
        
        #print("\n\nEpochs =",epoch_counter,"Mean Squared Error Loss =",neg_log_loss_initial,"\n\n")

        
        if abs(neg_log_loss_initial - neg_log_loss_final) < tol or invalid_value_flag == 1:
            print("\n\nEpochs =",epoch_counter,"Mean Squared Error Loss =",neg_log_loss_initial,"\n\n")
            break
            
    return {(step_size,reg_strength):[theta0_final,theta_final]}

In [53]:
def compute_mse(labels,predicted_labels):
    E = (labels - predicted_labels)
    return (1/labels.shape[0])*np.matmul(E.T,E)

In [54]:
def rmse(labels,trained_theta0,trained_theta,x_transpose):
    predicted_labels = predicted_answers(trained_theta0,trained_theta,x_transpose)
    return np.sqrt(compute_mse(labels,predicted_labels))

In [55]:
grid_search_results = list()
for step_size in [0.0000001,0.000001,0.00001]:
    for reg_hyp_param in [0.0001,0.001,0.01,0.1,1,10,100]:
        grid_search_results.append(fit(step_size,reg_hyp_param))



Epochs = 1 Mean Squared Error Loss = [[0.84422162]] 




Epochs = 1 Mean Squared Error Loss = [[0.72866156]] 




Epochs = 1 Mean Squared Error Loss = [[0.87103259]] 




Epochs = 1 Mean Squared Error Loss = [[0.7005264]] 




Epochs = 1 Mean Squared Error Loss = [[1.19042788]] 




Epochs = 1 Mean Squared Error Loss = [[0.67337873]] 




Epochs = 1 Mean Squared Error Loss = [[1.20191717]] 




Epochs = 8 Mean Squared Error Loss = [[0.62221552]] 




Epochs = 7 Mean Squared Error Loss = [[0.53732598]] 




Epochs = 2 Mean Squared Error Loss = [[0.68201416]] 




Epochs = 15 Mean Squared Error Loss = [[0.63261234]] 




Epochs = 15 Mean Squared Error Loss = [[0.65249992]] 




Epochs = 14 Mean Squared Error Loss = [[0.64859091]] 




Epochs = 16 Mean Squared Error Loss = [[0.75994252]] 




Epochs = 5502 Mean Squared Error Loss = [[0.28787441]] 




Epochs = 4853 Mean Squared Error Loss = [[0.2687874]] 




Epochs = 4404 Mean Squared Error Loss = [[0.31013945]] 




Epochs = 5053 Mean

In [56]:
y_cv = (y_cv - np.mean(y_cv))/np.std(y_cv)

In [57]:
grid_search_cv_results = dict()
for configs in grid_search_results:
    trained_params = list(configs.values())
    grid_search_cv_results[tuple(configs.keys())] = rmse(y_cv,trained_params[0][0],
                                                        trained_params[0][1],x_transpose_cv)

In [58]:
grid_search_cv_results

{((1e-07, 0.0001),): array([[0.99999905]]),
 ((1e-07, 0.001),): array([[0.99999907]]),
 ((1e-07, 0.01),): array([[0.99999903]]),
 ((1e-07, 0.1),): array([[0.9999991]]),
 ((1e-07, 1),): array([[0.99999906]]),
 ((1e-07, 10),): array([[0.99999923]]),
 ((1e-07, 100),): array([[0.99999904]]),
 ((1e-06, 0.0001),): array([[0.999925]]),
 ((1e-06, 0.001),): array([[0.99993177]]),
 ((1e-06, 0.01),): array([[0.99998064]]),
 ((1e-06, 0.1),): array([[0.99985662]]),
 ((1e-06, 1),): array([[0.99985497]]),
 ((1e-06, 10),): array([[0.9998647]]),
 ((1e-06, 100),): array([[0.99984565]]),
 ((1e-05, 0.0001),): array([[0.67499328]]),
 ((1e-05, 0.001),): array([[0.69721479]]),
 ((1e-05, 0.01),): array([[0.71495485]]),
 ((1e-05, 0.1),): array([[0.69682436]]),
 ((1e-05, 1),): array([[0.8049841]]),
 ((1e-05, 10),): array([[0.95253792]]),
 ((1e-05, 100),): array([[0.99447381]])}

In [59]:
grid_search_train_results = dict()
for configs in grid_search_results:
    trained_params = list(configs.values())
    grid_search_train_results[tuple(configs.keys())] = rmse(y_train,trained_params[0][0],
                                                        trained_params[0][1],x_transpose_train)

In [60]:
grid_search_train_results

{((1e-07, 0.0001),): array([[0.99999902]]),
 ((1e-07, 0.001),): array([[0.99999905]]),
 ((1e-07, 0.01),): array([[0.999999]]),
 ((1e-07, 0.1),): array([[0.99999906]]),
 ((1e-07, 1),): array([[0.99999901]]),
 ((1e-07, 10),): array([[0.99999919]]),
 ((1e-07, 100),): array([[0.99999902]]),
 ((1e-06, 0.0001),): array([[0.99992184]]),
 ((1e-06, 0.001),): array([[0.99992961]]),
 ((1e-06, 0.01),): array([[0.99997979]]),
 ((1e-06, 0.1),): array([[0.99985057]]),
 ((1e-06, 1),): array([[0.99985053]]),
 ((1e-06, 10),): array([[0.9998593]]),
 ((1e-06, 100),): array([[0.99983987]]),
 ((1e-05, 0.0001),): array([[0.65060969]]),
 ((1e-05, 0.001),): array([[0.67574181]]),
 ((1e-05, 0.01),): array([[0.6957826]]),
 ((1e-05, 0.1),): array([[0.67539775]]),
 ((1e-05, 1),): array([[0.79406502]]),
 ((1e-05, 10),): array([[0.95050644]]),
 ((1e-05, 100),): array([[0.99425899]])}

In [61]:
random_search_results = list()
for i in range(200):
    step_size = np.random.uniform(low=10**(-7),high=10**(-4))
    reg_hyp_param = np.random.uniform(low=10**(-4),high=10**(3))
    random_search_results.append(fit(step_size,reg_hyp_param))



Epochs = 39 Mean Squared Error Loss = [[0.73330684]] 




Epochs = 23 Mean Squared Error Loss = [[0.75765015]] 




Epochs = 60 Mean Squared Error Loss = [[0.87615112]] 




Epochs = 18 Mean Squared Error Loss = [[0.68278802]] 




Epochs = 30 Mean Squared Error Loss = [[0.87061645]] 




Epochs = 29 Mean Squared Error Loss = [[0.59072689]] 




Epochs = 205 Mean Squared Error Loss = [[0.6701813]] 




Epochs = 132 Mean Squared Error Loss = [[0.88393386]] 




Epochs = 1 Mean Squared Error Loss = [[1.2433484]] 




Epochs = 16 Mean Squared Error Loss = [[0.8384339]] 




Epochs = 17 Mean Squared Error Loss = [[0.87174052]] 




Epochs = 69 Mean Squared Error Loss = [[0.83504709]] 




Epochs = 14 Mean Squared Error Loss = [[0.73584383]] 




Epochs = 10 Mean Squared Error Loss = [[0.77664353]] 




Epochs = 55 Mean Squared Error Loss = [[0.69960243]] 




Epochs = 42 Mean Squared Error Loss = [[0.87375873]] 




Epochs = 24 Mean Squared Error Loss = [[0.93345418]] 




Epochs = 32 Me



Epochs = 91 Mean Squared Error Loss = [[0.9114947]] 




Epochs = 25 Mean Squared Error Loss = [[0.74373982]] 




Epochs = 13 Mean Squared Error Loss = [[0.90578923]] 




Epochs = 17 Mean Squared Error Loss = [[0.7707919]] 




Epochs = 30 Mean Squared Error Loss = [[0.89042667]] 




Epochs = 14 Mean Squared Error Loss = [[0.87924808]] 




Epochs = 16 Mean Squared Error Loss = [[0.74567186]] 




Epochs = 7 Mean Squared Error Loss = [[0.83600364]] 




Epochs = 77 Mean Squared Error Loss = [[0.7924658]] 




Epochs = 45 Mean Squared Error Loss = [[0.78217313]] 




Epochs = 19 Mean Squared Error Loss = [[0.83247465]] 




Epochs = 59 Mean Squared Error Loss = [[0.60634289]] 




Epochs = 15 Mean Squared Error Loss = [[0.68307547]] 




Epochs = 8 Mean Squared Error Loss = [[0.53128244]] 




Epochs = 59 Mean Squared Error Loss = [[1.01968535]] 




Epochs = 29 Mean Squared Error Loss = [[0.97652172]] 




Epochs = 52 Mean Squared Error Loss = [[0.84416843]] 




Epochs = 26 Mean 

In [62]:
random_search_results

[{(3.3514691853060754e-05, 937.7658335356012): [-0.00010631195973232369,
   array([[ 3.42132646e-04],
          [-4.27605566e-06],
          [ 1.97054857e-04],
          [ 4.04156980e-05],
          [ 8.46201329e-04],
          [-5.39472204e-05],
          [ 7.56625191e-05],
          [-5.89321334e-05],
          [ 3.43982103e-05]])]},
 {(2.915271340037707e-06, 980.780542252219): [8.688030094121232e-07,
   array([[ 1.92205815e-04],
          [-7.56720936e-06],
          [ 1.03678082e-04],
          [ 2.58350948e-05],
          [ 4.49620471e-04],
          [-2.52985322e-05],
          [ 3.13503394e-05],
          [-2.47988443e-05],
          [ 1.75826422e-05]])]},
 {(8.572802280704716e-05, 723.622528239817): [-0.0006863291962839749,
   array([[ 4.25797501e-04],
          [-7.36360341e-05],
          [ 2.46585542e-04],
          [ 5.32637115e-05],
          [ 1.04598558e-03],
          [-5.85923184e-05],
          [ 1.18988099e-04],
          [-1.05074418e-04],
          [ 4.02315079e-05

In [63]:
random_search_train_results = dict()
for configs in random_search_results:
    trained_params = list(configs.values())
    random_search_train_results[tuple(configs.keys())] = rmse(y_train,trained_params[0][0],
                                                        trained_params[0][1],x_transpose_train)

In [64]:
random_search_train_results

{((3.3514691853060754e-05, 937.7658335356012),): array([[0.99917796]]),
 ((2.915271340037707e-06, 980.780542252219),): array([[0.99956063]]),
 ((8.572802280704716e-05, 723.622528239817),): array([[0.99897836]]),
 ((4.056551841705976e-05, 377.38870901672976),): array([[0.99802378]]),
 ((6.986660855011286e-05, 362.9791733947052),): array([[0.99794413]]),
 ((4.832500100665416e-06, 414.66771399797926),): array([[0.99901819]]),
 ((6.362796358312457e-05, 18.73337665437849),): array([[0.9630756]]),
 ((8.640071038844874e-05, 88.82068360429719),): array([[0.99144489]]),
 ((1.459287032533063e-07, 34.64895183798502),): array([[0.99999851]]),
 ((3.6722339619471934e-05, 903.0177228555928),): array([[0.99918318]]),
 ((2.7539289130738257e-05, 394.4476815948888),): array([[0.99821931]]),
 ((8.525687980683891e-05, 108.37439165816564),): array([[0.99296517]]),
 ((6.876950937653306e-05, 333.70251276327997),): array([[0.99771468]]),
 ((4.306618549653553e-05, 682.3410679326454),): array([[0.99892712]]),
 (

In [65]:
random_search_cv_results = dict()
for configs in random_search_results:
    trained_params = list(configs.values())
    random_search_cv_results[tuple(configs.keys())] = rmse(y_cv,trained_params[0][0],
                                                        trained_params[0][1],x_transpose_cv)

In [66]:
random_search_cv_results

{((3.3514691853060754e-05, 937.7658335356012),): array([[0.9992086]]),
 ((2.915271340037707e-06, 980.780542252219),): array([[0.9995789]]),
 ((8.572802280704716e-05, 723.622528239817),): array([[0.99900794]]),
 ((4.056551841705976e-05, 377.38870901672976),): array([[0.99810978]]),
 ((6.986660855011286e-05, 362.9791733947052),): array([[0.9980289]]),
 ((4.832500100665416e-06, 414.66771399797926),): array([[0.99905711]]),
 ((6.362796358312457e-05, 18.73337665437849),): array([[0.96451282]]),
 ((8.640071038844874e-05, 88.82068360429719),): array([[0.99180981]]),
 ((1.459287032533063e-07, 34.64895183798502),): array([[0.99999857]]),
 ((3.6722339619471934e-05, 903.0177228555928),): array([[0.99921419]]),
 ((2.7539289130738257e-05, 394.4476815948888),): array([[0.99829101]]),
 ((8.525687980683891e-05, 108.37439165816564),): array([[0.99324752]]),
 ((6.876950937653306e-05, 333.70251276327997),): array([[0.99778228]]),
 ((4.306618549653553e-05, 682.3410679326454),): array([[0.99896214]]),
 ((2

In [67]:
random_search_results = list()
for i in range(10):
    step_size = np.random.uniform(low=10**(-5),high=9*(10**(-5)))
    reg_hyp_param = np.random.uniform(low=10**(-2),high=9*(10**(-2)))
    random_search_results.append(fit(step_size,reg_hyp_param))



Epochs = 2032 Mean Squared Error Loss = [[0.28444305]] 




Epochs = 1670 Mean Squared Error Loss = [[0.20710127]] 




Epochs = 4030 Mean Squared Error Loss = [[0.27995095]] 




Epochs = 2302 Mean Squared Error Loss = [[0.23229121]] 




Epochs = 2151 Mean Squared Error Loss = [[0.24404672]] 




Epochs = 2139 Mean Squared Error Loss = [[0.26256269]] 




Epochs = 2928 Mean Squared Error Loss = [[0.19706185]] 




Epochs = 1785 Mean Squared Error Loss = [[0.28526313]] 




Epochs = 2109 Mean Squared Error Loss = [[0.25306794]] 




Epochs = 2847 Mean Squared Error Loss = [[0.26096813]] 




In [68]:
random_search_cv_results = dict()
for configs in random_search_results:
    trained_params = list(configs.values())
    random_search_cv_results[tuple(configs.keys())] = rmse(y_cv,trained_params[0][0],
                                                        trained_params[0][1],x_transpose_cv)

In [69]:
random_search_train_results = dict()
for configs in random_search_results:
    trained_params = list(configs.values())
    random_search_train_results[tuple(configs.keys())] = rmse(y_train,trained_params[0][0],
                                                        trained_params[0][1],x_transpose_train)

In [70]:
random_search_cv_results

{((8.053869612891693e-05, 0.059777087143110905),): array([[0.55744539]]),
 ((8.559593787341368e-05, 0.06799027233007841),): array([[0.56499206]]),
 ((2.062117825317931e-05, 0.011562305845977044),): array([[0.60962851]]),
 ((7.346832525730211e-05, 0.023218031378289664),): array([[0.5530568]]),
 ((4.5559057637018044e-05, 0.018698254233752848),): array([[0.59024878]]),
 ((8.860538860875287e-05, 0.019567554571828003),): array([[0.55014762]]),
 ((4.864625260937906e-05, 0.06491224357391358),): array([[0.56454751]]),
 ((8.045484546125058e-05, 0.05608285834721336),): array([[0.56303062]]),
 ((7.320446677885092e-05, 0.0442370176919998),): array([[0.55817162]]),
 ((4.671682937157787e-05, 0.020777020514718778),): array([[0.56381303]])}

In [71]:
random_search_train_results

{((8.053869612891693e-05, 0.059777087143110905),): array([[0.50669527]]),
 ((8.559593787341368e-05, 0.06799027233007841),): array([[0.51733008]]),
 ((2.062117825317931e-05, 0.011562305845977044),): array([[0.57432785]]),
 ((7.346832525730211e-05, 0.023218031378289664),): array([[0.50015139]]),
 ((4.5559057637018044e-05, 0.018698254233752848),): array([[0.55035691]]),
 ((8.860538860875287e-05, 0.019567554571828003),): array([[0.4952158]]),
 ((4.864625260937906e-05, 0.06491224357391358),): array([[0.51673187]]),
 ((8.045484546125058e-05, 0.05608285834721336),): array([[0.5147207]]),
 ((7.320446677885092e-05, 0.0442370176919998),): array([[0.50789759]]),
 ((4.671682937157787e-05, 0.020777020514718778),): array([[0.51575516]])}

In [72]:
from sklearn.preprocessing import PolynomialFeatures

In [73]:
feature_engineering_obj = PolynomialFeatures()

In [74]:
x_transpose_quadratic = feature_engineering_obj.fit_transform(X=x_transpose)

In [75]:
x_transpose_quadratic = x_transpose_quadratic[:,1:]

In [77]:
x_transpose_quadratic_train = x_transpose_quadratic[0:int(0.7*x_transpose.shape[0])]
x_transpose_quadratic_cv = x_transpose_quadratic[int(0.7*x_transpose.shape[0]):int(0.9*x_transpose.shape[0])]
x_transpose_quadratic_test = x_transpose_quadratic[int(0.9*x_transpose.shape[0]):]

In [78]:
from sklearn.linear_model import LinearRegression

In [79]:
lr_obj = LinearRegression()

In [82]:
lr_obj.fit(X=x_transpose_quadratic_train,y=y_train)

LinearRegression()

In [83]:
theta_trained = lr_obj.coef_

In [84]:
theta_trained = theta_trained.reshape(theta_trained.shape[1],1)

In [85]:
theta_trained.shape

(54, 1)

In [86]:
theta0_trained = lr_obj.intercept_

In [87]:
theta0_trained

array([1.76768127e+13])

In [89]:
train_rmse = rmse(y_train,theta0_trained,theta_trained,x_transpose_quadratic_train)

In [90]:
train_rmse

array([[0.37234175]])

In [91]:
cv_rmse = rmse(y_cv,theta0_trained,theta_trained,x_transpose_quadratic_cv)

In [92]:
cv_rmse

array([[0.44806556]])

In [93]:
feature_engineering_obj = PolynomialFeatures(degree=3)

In [94]:
x_transpose_cubic = feature_engineering_obj.fit_transform(X=x_transpose)

In [95]:
x_transpose_cubic = x_transpose_cubic[:,1:]

In [96]:
x_transpose_cubic_train = x_transpose_cubic[0:int(0.7*x_transpose.shape[0])]
x_transpose_cubic_cv = x_transpose_cubic[int(0.7*x_transpose.shape[0]):int(0.9*x_transpose.shape[0])]
x_transpose_cubic_test = x_transpose_cubic[int(0.9*x_transpose.shape[0]):]

In [97]:
lr_obj = LinearRegression()

In [98]:
lr_obj.fit(X=x_transpose_cubic_train,y=y_train)

LinearRegression()

In [99]:
theta_trained = lr_obj.coef_
theta_trained = theta_trained.reshape(theta_trained.shape[1],-1)

In [100]:
theta_trained.shape

(219, 1)

In [101]:
theta0_trained = lr_obj.intercept_

In [103]:
train_rmse = rmse(y_train,theta0_trained,theta_trained,x_transpose_cubic_train)

In [104]:
train_rmse

array([[0.35751653]])

In [105]:
cv_rmse = rmse(y_cv,theta0_trained,theta_trained,x_transpose_cubic_cv)

In [106]:
cv_rmse

array([[0.45344014]])